### ISSUE TITLE
Error - Note Sure what it is

### ISSUE THREAD

**Issue by renatoluz** [ccabrales/TabHero#2]
Could you guys help me with the error below?

![image](https://user-images.githubusercontent.com/44309436/51342913-45c02d00-1a7c-11e9-8c6e-0f5c5413de38.png)

**Comment by ccabrales** [comment]
See the discussion in issue #1. I'm guessing it's that the site changed their layout, so the scraping is broken. Feel free to jump in and make a PR to fix it.

**Comment by renatoluz** [comment]
ok, i'll see! thanks!
